create table if not exists public.case_update_requests (
  id bigint generated by default as identity primary key,
  content text not null,
  email text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  admin_note text,
  resolved_at timestamptz,
  constraint case_update_requests_content_check
    check (char_length(trim(content)) between 1 and 4000),
  constraint case_update_requests_email_check
    check (email is null or char_length(trim(email)) between 3 and 320),
  constraint case_update_requests_status_check
    check (status = any (array['pending'::text, 'reviewing'::text, 'completed'::text, 'rejected'::text]))
);

create index if not exists case_update_requests_status_created_at_idx
  on public.case_update_requests (status, created_at desc);

create or replace function public.set_case_update_request_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = current_timestamp;
  return new;
end;
$$;

drop trigger if exists set_case_update_request_updated_at on public.case_update_requests;

create trigger set_case_update_request_updated_at
before update on public.case_update_requests
for each row
execute function public.set_case_update_request_updated_at();

alter table public.case_update_requests enable row level security;

revoke all on table public.case_update_requests from anon, authenticated;
grant select, insert, update on table public.case_update_requests to service_role;
